# -*- coding: utf-8 -*-
"""
common/theme_tokens.py —— Gentelella v4 Light Mode 精确对齐。
来源：gentelella-master/src/scss/v4/_tokens.scss（亮色模式）
"""
# ---- 背景 ----
COLOR_BG_DARK = "#F5F7FB"
COLOR_BG_SURFACE = "#FFFFFF"
COLOR_BG_CARD = "#FFFFFF"

# ---- 文字 ----
COLOR_TEXT_PRIMARY = "#1E2633"
COLOR_TEXT_SECONDARY = "#626D7D"
COLOR_TEXT_DISABLED = "#7E8896"

# ---- 语义色 ----
COLOR_ACCENT = "#3B82F6"
COLOR_ACCENT_DK = "#2563EB"
COLOR_SUCCESS = "#2FB344"
COLOR_WARNING = "#F59F00"
COLOR_DANGER = "#D63939"
COLOR_INFO = "#4299E1"
COLOR_BORDER = "#E6E7EB"
COLOR_OFFLINE = "#7E8896"

# ---- Sidebar 暗色模式 ----
SIDEBAR_BG = "#1A2332"
SIDEBAR_TEXT = "#B3BCCB"
SIDEBAR_TEXT_HOVER = "#C5D0DC"
SIDEBAR_TEXT_ACTIVE = "#FFFFFF"
SIDEBAR_TEXT_MUTED = "#7B8FA3"
SIDEBAR_BORDER = "rgba(255,255,255,0.06)"
SIDEBAR_HOVER = "rgba(255,255,255,0.04)"
SIDEBAR_ACTIVE_BG = "rgba(59,130,246,0.12)"

# ---- 间距 (Gentelella 4px base) ----
SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 12
SPACING_LG = 16
SPACING_XL = 24
SPACING_XXL = 32

# ---- 字体 ----
FONT_FAMILY = "'Inter', 'Microsoft YaHei', 'Segoe UI', sans-serif"
FONT_SIZE_TITLE_LG = "24px"
FONT_SIZE_TITLE_MD = "20px"
FONT_SIZE_TITLE_SM = "16px"
FONT_SIZE_BODY = "14px"
FONT_SIZE_BODY_SM = "12px"
FONT_SIZE_CAPTION = "11px"
FONT_SIZE_NUMERIC_LG = "32px"
FONT_SIZE_NUMERIC_MD = "20px"

# ---- 圆角 ----
RADIUS_CARD = 8
RADIUS_BUTTON = 6
RADIUS_BADGE = 6
